server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/productos {
        proxy_pass http://producto-api:8080/api/productos;
    }
    
    location /api/inventarios {
        proxy_pass http://inventario-api:8081/api/inventarios;
    }
    
    location /api/usuarios {
        proxy_pass http://usuario-api:8082/api/usuarios;
    }
    
    location /api/pedidos {
        proxy_pass http://pedido-api:8083/api/pedidos;
    }
}
