CREATE TABLE inventario (
    inventario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    cantidad_disponible BIGINT NOT NULL,
    cantidad_reservada BIGINT NOT NULL,
    ultima_actualizacion TIMESTAMP(6) NOT NULL,
    CONSTRAINT inventario_cantidad_chk CHECK (cantidad_disponible >= 0 AND cantidad_reservada >= 0)
);
