CREATE TABLE reserva (
    reserva_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad BIGINT NOT NULL,
    fecha_reserva TIMESTAMP(6) NOT NULL,
    CONSTRAINT reserva_pedido_producto_uk UNIQUE (pedido_id, producto_id)
);
