spring.application.name=producto-api

# URL de la base de datos (la necesitamos siempre, en cualquier ambiente)
spring.datasource.url=jdbc:h2:mem:productodb

# Evita el warning de open-in-view
spring.jpa.open-in-view=false

# Le decimos a Spring que por defecto use el perfil de desarrollo
spring.profiles.default=dev

# Tamaño máximo de página que un cliente puede pedir (si pide más, se recorta a 50)
spring.data.web.pageable.max-page-size=50

server.port=8080

# URL base de inventario-api (al crear un producto se le pide crear su inventario)
inventario.api.url=http://localhost:8081

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
