# ==================================
# Configuración SOLO para desarrollo
# (Nunca debe llegar a producción)
# ==================================

# Ver el SQL que genera Hibernate en la consola
spring.jpa.show-sql=true

# Consola web de H2 (solo útil en local)
spring.h2.console.enabled=true