spring.application.name=producto-api

# URL de la base de datos (la necesitamos siempre, en cualquier ambiente)
spring.datasource.url=jdbc:h2:mem:productodb

# Silenciamos el warning de open-in-view (Punto 11 tachado!)
spring.jpa.open-in-view=false

# Le decimos a Spring que por defecto use el perfil de desarrollo
spring.profiles.default=dev