CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    nombre VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    CONSTRAINT usuario_rol_chk CHECK (rol IN ('USER','ADMIN')),
    CONSTRAINT usuario_estado_chk CHECK (estado IN ('ACTIVO','BAJA'))
);
