spring.application.name=pedido-api

# 1. Le decimos a Spring que queremos ver en la consola el código SQL que genera por detrás
spring.jpa.show-sql=true

# 2. Habilitamos una interfaz visual web para ver nuestra base de datos H2
spring.h2.console.enabled=true

# 3. Le damos un nombre fijo a nuestra base de datos para encontrarla fácil
spring.datasource.url=jdbc:h2:mem:pedidodb