server.port=8083
spring.application.name=pedido-api

spring.datasource.url=jdbc:h2:mem:pedidodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.profiles.default=dev
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.cloud.compatibility-verifier.enabled=false

api.producto.url=${PRODUCTO_URL:http://localhost:8080/api/productos}
api.inventario.url=${INVENTARIO_URL:http://localhost:8081/api/inventarios}
api.usuario.url=${USUARIO_URL:http://localhost:8082/api/usuarios}

seguridad.jwt.secret=${JWT_SECRET:d1f2g3h4j5k6l7m8n9q0w1e2r3t4y5u6i7o8p9z0x1c2v3b4n5m6_desarrollo_local}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

resilience4j.circuitbreaker.instances.inventario.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventario.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventario.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.inventario.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.inventario.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventario.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario.ignoreExceptions=io.github.danielmelejpinto.pedidoapi.exception.StockInsuficienteException,io.github.danielmelejpinto.pedidoapi.exception.DependenciaClienteException

resilience4j.circuitbreaker.instances.inventario-liberar.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventario-liberar.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventario-liberar.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventario-liberar.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventario-liberar.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventario-liberar.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario-liberar.ignoreExceptions=io.github.danielmelejpinto.pedidoapi.exception.DependenciaClienteException
