spring.application.name=inventario-api

# 1. El puerto
server.port=8081

# 2. Configuración de H2
spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Le decimos a JPA que cree las tablas por nosotros
spring.jpa.hibernate.ddl-auto=update

# 4. Apagamos Flyway temporalmente para que no busque scripts SQL
spring.flyway.enabled=false

# Evita el warning de open-in-view
spring.jpa.open-in-view=false