CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    tipo_evento VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    intentos INTEGER NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    CONSTRAINT outbox_estado_chk CHECK (estado IN ('PENDIENTE','ENVIADO','ERROR')),
    CONSTRAINT outbox_tipo_chk CHECK (tipo_evento IN ('CREACION'))
);

CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(1000),
    imagen_url VARCHAR(2000),
    precio NUMERIC(12,2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecha_creacion TIMESTAMP(6) NOT NULL,
    CONSTRAINT producto_estado_chk CHECK (estado IN ('PENDIENTE','ACTIVO','BAJA'))
);
